"""
WireGuard helpers: key generation, config building, service management.
"""

import asyncio
import ipaddress
import json
import logging
import re
import socket
import subprocess
from typing import Any

from sqlmodel import select

from ..config import CONFIG_FILE
from ..database import AsyncSessionLocal
from ..models import GlobalSettings, WireGuardClient, WireGuardServer

logger = logging.getLogger(__name__)


class WireGuardError(Exception):
    """Raised when a wg / wg-quick command fails."""


async def _run(cmd: str) -> str:
    """Run a shell command and return stripped stdout. Raises WireGuardError on failure."""
    proc = await asyncio.create_subprocess_shell(
        cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()
    if proc.returncode != 0:
        raise WireGuardError(stderr.decode().strip() or f"Command failed: {cmd}")
    return stdout.decode().strip()


# ── Key management ────────────────────────────────────────────────────────────


async def generate_keypair() -> dict[str, str]:
    """Generate a fresh WireGuard private/public key pair."""
    private_key = await _run("wg genkey")
    public_key = await _run(f"echo {private_key} | wg pubkey")
    return {"private_key": private_key, "public_key": public_key}


# ── Service control ───────────────────────────────────────────────────────────


async def get_service_state(interface: str = "wg0") -> str:
    """Return 'running' if the interface is up, 'stopped' otherwise."""
    try:
        await _run(f"wg showconf {interface}")
        return "running"
    except WireGuardError:
        return "stopped"


async def start_service(interface: str = "wg0") -> None:
    try:
        await _run(f"wg-quick up {interface}")
        logger.info("Wireguard started.")
    except WireGuardError as exc:
        raise WireGuardError(f"Start failed: {exc}") from exc


async def stop_service(interface: str = "wg0") -> None:
    try:
        await _run(f"wg-quick down {interface}")
        logger.info("Wireguard stopped.")
    except WireGuardError as exc:
        raise WireGuardError(f"Stop failed: {exc}") from exc


async def restart_service(interface: str = "wg0") -> None:
    try:
        await stop_service(interface)
    except WireGuardError:
        pass  # may already be down
    await start_service(interface)


# ── Status ────────────────────────────────────────────────────────────────────


async def get_status() -> dict[str, Any]:
    """Parse `wg show` output and return structured status data."""
    state = await get_service_state()
    if state == "stopped":
        return {"state": "stopped", "interface": None, "peers": []}

    try:
        output = await _run("wg show")
    except WireGuardError:
        return {"state": "error", "interface": None, "peers": []}

    peers: list[dict[str, Any]] = []
    current_peer: dict[str, Any] = {}
    interface_name: str | None = None

    for line in output.splitlines():
        line = line.strip()
        if line.startswith("interface:"):
            interface_name = line.split(":", 1)[1].strip()
        elif line.startswith("peer:"):
            if current_peer:
                peers.append(current_peer)
            current_peer = {"public_key": line.split(":", 1)[1].strip()}
        elif line.startswith("endpoint:"):
            current_peer["endpoint"] = line.split(":", 1)[1].strip()
        elif line.startswith("latest handshake:"):
            current_peer["latest_handshake"] = line.split(":", 1)[1].strip()
        elif line.startswith("transfer:"):
            m = re.match(
                r"([\d.]+ \w+) received, ([\d.]+ \w+) sent",
                line.split(":", 1)[1].strip(),
            )
            if m:
                current_peer["transfer_rx"] = m.group(1)
                current_peer["transfer_tx"] = m.group(2)
        elif line.startswith("allowed ips:"):
            current_peer["allowed_ips"] = line.split(":", 1)[1].strip()

    if current_peer:
        peers.append(current_peer)

    return {"state": "running", "interface": interface_name, "peers": peers}


# ── Config builders ───────────────────────────────────────────────────────────


def build_client_config(
    client: WireGuardClient, server: WireGuardServer, settings: GlobalSettings
) -> str:
    lines = [
        "# WireGuard client configuration — generated by WireGuard UI",
        f"# Client : {client.name} ({client.email})",
        "",
        "[Interface]",
        f"Address    = {client.allocated_ips}",
        f"PrivateKey = {client.private_key}",
    ]
    if client.use_server_dns and settings.dns_servers:
        lines.append(f"DNS = {','.join(settings.dns_servers)}")
    if settings.mtu is not None:
        lines.append(f"MTU = {settings.mtu}")

    lines += [
        "",
        "[Peer]",
        f"PublicKey  = {server.public_key}",
        f"Endpoint   = {settings.endpoint_address}:{server.listen_port}",
        f"AllowedIPs = {','.join(client.allowed_ips)}",
    ]
    if settings.persistent_keepalive:
        lines.append(f"PersistentKeepalive = {settings.persistent_keepalive}")
    if client.preshared_key:
        lines.append(f"PresharedKey = {client.preshared_key}")

    return "\n".join(lines)


def build_server_config(server: WireGuardServer, clients: list[WireGuardClient]) -> str:
    try:
        net = ipaddress.ip_network(server.address, strict=False)
        server_ip = str(list(net.hosts())[0])
    except Exception:
        server_ip = server.address

    lines = [
        "# WireGuard server configuration — generated by WireGuard UI",
        "",
        "[Interface]",
        f"Address    = {server_ip}",
        f"ListenPort = {server.listen_port}",
        f"PrivateKey = {server.private_key}",
    ]
    if server.postup:
        lines.append(f"PostUp   = {server.postup}")
    if server.postdown:
        lines.append(f"PostDown = {server.postdown}")

    for c in clients:
        if not c.enabled:
            continue
        lines += [
            "",
            f"# Peer: {c.name} ({c.email})",
            "[Peer]",
            f"PublicKey  = {c.public_key}",
            f"AllowedIPs = {c.allocated_ips}",
        ]
        if c.preshared_key:
            lines.append(f"PresharedKey = {c.preshared_key}")

    return "\n".join(lines)


async def write_server_config() -> None:
    """Write the server config file to disk (async executor to avoid blocking)."""

    async with AsyncSessionLocal() as db:
        server = (await db.exec(select(WireGuardServer))).one_or_none()
        clients = list((await db.exec(select(WireGuardClient))).all())

    if not server:
        raise WireGuardError("Server not configured")

    def _write_config_file(path: str, data: str) -> None:
        with open(path, "w", encoding="utf-8") as config_file:
            config_file.write(data)

    content = build_server_config(server, clients)
    loop = asyncio.get_event_loop()
    await loop.run_in_executor(None, _write_config_file, CONFIG_FILE, content)


# ── Network utils ─────────────────────────────────────────────────────────────


def get_machine_ips() -> list[dict[str, str]]:
    """Return all non-loopback IP addresses on the host."""
    result: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()

    try:
        output = subprocess.run(
            ["ip", "-j", "address", "show"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout
        for iface in json.loads(output):
            name = iface.get("ifname", "")
            for addr in iface.get("addr_info", []):
                ip = str(addr.get("local", "")).split("%", 1)[0]
                if not ip or ip.startswith("127.") or ip == "::1":
                    continue
                key = (name, ip)
                if key in seen:
                    continue
                seen.add(key)
                result.append({"name": name, "ip_address": ip})
        return result
    except Exception:
        # Fallback for hosts without the `ip` command available.
        try:
            host = socket.gethostname()
            for family, _, _, _, sockaddr in socket.getaddrinfo(host, None):
                if family not in (socket.AF_INET, socket.AF_INET6):
                    continue
                ip = str(sockaddr[0]).split("%", 1)[0]
                if not ip or ip.startswith("127.") or ip == "::1":
                    continue
                key = ("host", ip)
                if key in seen:
                    continue
                seen.add(key)
                result.append({"name": "host", "ip_address": ip})
        except Exception:
            return []

    return result
