[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid
loglevel = INFO

# [program:alembic]
# command=alembic upgrade head
# user=root
# directory=/app
# autostart=true
# redirect_stderr=true
# stdout_logfile=/dev/stdout
# stdout_logfile_maxbytes=0
# stderr_logfile=/dev/stderr
# stderr_logfile_maxbytes=0
# priority=1

[program:fastapi]
# command=fastapi run src/main.py --port 8000
command=uvicorn backend.main:app --host 0.0.0.0  --port 8000 --workers 2
user=root
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=2
