"""Update password length

Revision ID: 6c9060db3198
Revises: 8ddd237ecdd6
Create Date: 2024-02-11 15:22:19.414775

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6c9060db3198"
down_revision = "c7d89d28d3e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.create_unique_constraint("us_phone_number", ["us_phone_number"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=255), nullable=False
        )

    # ### end Alembic commands ###
