"""Add column fs_webauthn_user_handle

Revision ID: 8ddd237ecdd6
Revises: 
Create Date: 2024-02-11 14:53:39.710215

"""
import flask_security
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8ddd237ecdd6"
down_revision = "8c65941b01c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("fs_webauthn_user_handle", sa.String(64), nullable=True)
        )
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.add_column(sa.Column("mf_recovery_codes", sa.TEXT, nullable=True))
        batch_op.create_unique_constraint("us_phone_number", ["us_phone_number"])
        batch_op.create_unique_constraint(
            "fs_webauthn_user_handle", ["fs_webauthn_user_handle"]
        )

    op.create_table(
        "web_authn",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("credential_id", sa.LargeBinary(length=1024), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=True),
        sa.Column("transports", flask_security.datastore.AsaList(), nullable=True),
        sa.Column("backup_state", sa.Boolean(), nullable=False),
        sa.Column("device_type", sa.String(length=64), nullable=False),
        sa.Column("extensions", sa.String(length=255), nullable=True),
        sa.Column(
            "create_datetime",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("lastuse_datetime", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("usage", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("web_authn", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_web_authn_credential_id"), ["credential_id"], unique=True
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("fs_webauthn_user_handle")
        batch_op.drop_column("mf_recovery_codes")
        batch_op.drop_constraint("us_phone_number", type_="unique")
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.drop_constraint("us_phone_number", type_="unique")
        batch_op.drop_constraint("fs_webauthn_user_handle", type_="unique")

    with op.batch_alter_table("webauthn", schema=None) as batch_op:
        batch_op.drop_index("ix_webauthn_credential_id")

    op.drop_table("webauthn")
    # ### end Alembic commands ###
